apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ea0i46c1z-java-quarkus 
  janus-idp.io/tekton: ea0i46c1z-java-quarkus
  backstage.io/kubernetes-id: ea0i46c1z-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ea0i46c1z-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  